[package]
name = "mousefood"
description = "embedded-graphics backend for Ratatui"
version = "0.0.1"
edition = "2021"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/j-g00da/mousefood"
repository = "https://github.com/j-g00da/mousefood"
keywords = ["embedded-graphics", "ratatui", "tui"]
categories = ["embedded"]

[dependencies]
ratatui = { version = "0.29", default-features = false, features = ["all-widgets"] }
embedded-graphics = "0.8.1"
