name: Changelog

on:
  pull_request:
    types:
      - opened,
      - reopened,
      - labeled,
      - unlabeled,
      - synchronize
    branches:
      - main

jobs:
  changelog:
    name: Check if changelog was updated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dangoslen/changelog-enforcer@v3
        with:
          skipLabels: "skip-changelog"
          missingUpdateErrorMessage: "Please add a changelog entry in the CHANGELOG.md file."
